### PR TITLE
Add profile pictures to team section on about-us page

### PR DESCRIPTION
**Pull request by todueke**
#### What Does this PR do?
- Adds profile picture to team section on the About Us page.

### CODE REVIEW

**Review by olahsymbo100 — COMMENTED** [review]
LGTM!

**Comment by todueke** [comment]
> LGTM!

Thanks, but seems like you just added a comment, you didn't approve

**Comment by Engineering-Phyna** [comment]
Go ahead and merge!

**Review by olahsymbo100 — APPROVED** [review]
Sorry I forgot to approve it.

**Pull request merged**
